### ISSUE TITLE
Error compiling CSS package "catalog"

### ISSUE THREAD

**Issue by SimranjitSinghMonga** [mysteryjeans/doorstep#10]
Errors:

[WinError 2] The system cannot find the file specified

**Comment by alsonpr** [comment]
I'm having the same issue. Did anyone found any solution to this?

**Comment by mysteryjeans** [comment]
You need nodejs and yuglify & less as global modules to compile css

**Comment by alsonpr** [comment]
Thanks that helped.

**Comment by Vishnu-Chittan** [comment]
> Errors:
> 
> [WinError 2] The system cannot find the file specified

Same Issue I got
Even I put the nodejs as global, but unluckily got the same error

![image](https://user-images.githubusercontent.com/31886444/74638694-67fe1000-5192-11ea-90a6-0c1cdec02ac6.png)
